---
title: "Term project: Proposal "
output:
  html_document:
    df_print: paged
---


Total points: 10 pts

- Questions 2
- Data provided and read into R 1
- Data description 3 
- Visualization ideas 3
- References 1


# Term project

What is it?

Your term project is an analysis on a dataset of your own choosing. 

You can choose the data based on your interests, based on work in other courses, or independent research projects. 

You should demonstrate *many* of the techniques from the course, applying them as appropriate to develop and *communicate insight into the data*.

You should create several (5+) *compelling visualizationS* of your data. 

Pay attention to your presentation: neatness, coherency, and clarity will count. 

All analyses must be done in RStudio using R.


# Deliverables

Work in groups of 1, 2 or 3. 

Each team should produce one common submission of each component (proposal, report, presentation)

However, each of these components should contain, beside one common contribution from the entire team, sections that are specifically signed by individual Team members.

I will give more instructions on this below.

Each team member has two roles in the project. First you will contribute your original creative work for the project. Second, you will act as a collaborator, providing your teammate with feedback, suggestions, debugging help, proofreading and other assistance as requested.

You will use BS to upload the term project proposal

The other components of the term project (final written report and the oral presentation) are not due till April.

Note that I will create separate drop-boxes on BS for each of these submissions (again: they are not due at the same time).


# Team creation

You team with whomever you want. By now, you should have logged an entry in the BS quiz 'STAT2430FinalProject2025Teams'.


# Proposal



Your main task for the proposal is to 

1. find a data set to analyze for your project and 
2. describe at least one question you can address with data visualizations.

It is important that you choose a readily accessible data set that is large enough so multiple relationships can be explored, but no so complex that you get lost. 

I suggest your data set should have at least 100 observations and about 10 variables or more (including 2+ categorical variables and 4+ quantitative variables).

I also suggest that you choose a dataset for which you find a reasonably good description/documentation of each column, context of collection, goal of data collection etc.

Remember the who, why, when, where, how question about data collection. This is a very good set of questions to ask in your proposal and later final report.

Data that contain an indicate of time (e.e. column of dates) and/or space (longitude and latitude) are interesting because these variables have a very natural interpretation and give you access to plots or data analyses such as time series or maps. I personally like this.


If you find a very large data set, you can make a subset to work with for your project. The data set must include categorical and quantitative variables. If you plan to use a data set that comes in a format that we haven’t encountered in class, make sure that you are able to load it into R as this can be a challenging task. If you are having trouble ask for help before it is too late.

Do not reuse the data sets from my lectures. 

Some examples of datasets are posted on BS.

Here is list of data repositories containing many interesting datasets. 
Feel free to use data from other sources if you prefer.

* [TidyTuesday](https://github.com/rfordatascience/tidytuesday)
* [Kaggle](https://www.kaggle.com/datasets) 
* [OpenIntro](https://www.openintro.org/book/statdata/index.php) 
* [Awesome public](https://github.com/awesomedata/awesome-public-datasets) datasets
* [Bikeshare](https://www.bikeshare.com/data/) data portal
* [Harvard Dataverse](https://dataverse.harvard.edu/)
* [Statistics Canada](https://www150.statcan.gc.ca/n1/en/type/data)
* Open government data: [Canada](https://open.canada.ca/en/open-data), [NS](https://data.novascotia.ca/), and many other sources
* Other sources listed in the [Data sources](#data-sources) section of these notes
* Data you find on your own may be suitable too.



This is what you need to do for your proposal:

1. find a proper dataset. 
2. Describe the data set and question you can address with the data for your proposal. 
3. Outline a plan to use about *five visualizations* (e.g., data overview plot, dplyr/table summary, small multiples, smoothing/regression, k-means/PCA, map).


Many data sets on Kaggle are simulated data – generated by a computer with randomization and not the result of a real-life data-gathering process. You can recognize these data because there is no clear explanation of how the data were collected. Do not use simulated data. Do not use data if you can’t explain how it was collected.

The repository contains a template for your proposal called proposal.Rmd. 


Write your proposal by revising this file and using this template.

1. Questions: The introduction should introduce your research questions
2. Data: Describe the data (where it came from, how it was collected, what are the cases, what are the variables, etc.). Place your data in the /data folder. Show that you can read the data and include the output of dplyr::glimpse() or skimr::skim() on your data in the proposal. Do not show the entire dataset.
3. Visualization plan:

- The outcome (response, Y) and predictor (explanatory, X) variables you will use to answer your question.

- Ideas for at least two possible visualizations for exploratory data analysis, including some summary statistics and visualizations, along with some explanation on how they help you learn more about your data.

- An idea of how at least one statistical method described in the course (smoothing, PCA, k-means) could be useful in analyzing your data

- Team planning: briefly describe how members of your team will divide the tasks to be performed.




